[project]
name = "book-recommender"
version = "0.1.0"
description = "Book Recommendations using UCSD Goodreads Data"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "black",
    "fastparquet",
    "fuzzywuzzy[speedup]",
    "gdown",
    "implicit",
    "ipykernel",
    "jupyter",
    "lightgbm",
    "loguru",
    "pandas",
    "plotly",
    "pyarrow",
    "matplotlib",
    "seaborn",
    "scipy",
    "tqdm",
]

[tool.black]
line-length = 120

[tool.ruff]
line-length = 120

[tool.hatch.build.targets.wheel]
packages = ["src"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "coverage>=7.13.0",
    "pytest>=9.0.2",
    "ruff>=0.14.10",
]
